before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends latexmk
  texlive-fonts-extra texlive-fonts-recommended texlive-latex-base texlive-latex-extra
  texlive-latex-recommended
script:
- mkdir _build
- latexmk -pdf -outdir=_build cs203S2019_syllabus.tex
deploy:
  provider: releases
  api_key:
    secure: NEuX06NwC3NIPaVn5x7y7Nn0uKwlBZBxR3eKsW86uKHT1hZUgcCsun1ZzeJZLffnz5naoS3SWQYswI09sQ0b4DRw3arQBmBiwCcXLEEsnV0hPAXs2MxLbSbqWaRKFd/7a9T/Zvg6SnNuFt74h3k+SiP6JhNNCW2HahKPTNOFH+x7wGdeMb/MM5F4iQWH7C1lQJHJVMOjA8s/QHtr03LhNpjAHM6SCqCBdF7tZp/UNcMhK0m0H1bX7MHGv8O4YCyZqelFxbljgckDJvChQOoxMDka9Dz+IyE0TrpZl1kHpRqjFdzvXLMSN5ocKQFcsdNadDJ8vRcHDUTlBIk9SsldZFF5MKfNXltqQ7a7KQUsa0gaR8BW5zYgluITU509sAeXL3VQJ6MwHU4oVNBGJ9hk55GuX5iul8cD+xR8pNxw6PzBkuk8lCBwMeVDGP4z4l5CQ0GHGok9wqcGac375hf3Pd86Q2epKpLUNMI8b3pTH60GPGPRUgsiX/GPSwyjXiIWNPbtNzT3WGi4Wbk7YJxXhkSvdjvZJqueC7NBfmeJeKrrzYjxFEHC6Y5s5fM2diBhes5YD4qR31aCqN0y//XFwI3x6N5OM1TaK/UFtb6Hr3MFQALJaHgLnmXbhvjqR3vfapg9reKoF2XLxpPvO0TeJom0772xMQwuUu8xD8BfdLw=
  file: _build/cs203S2019_syllabus.pdf
  skip_cleanup: true
  on:
    tags: true
